print("Tenth Score Details")
tam=int(input("Enter Tamil Mark"'\t'))
eng=int(input("Enter English Mark"'\t'))
mat=int(input("Enter Maths Mark"'\t'))
sci=int(input("Enter Science Mark"'\t'))
soc=int(input("Enter Social Mark"'\t'))
print(tam)
print(eng)
print(mat)
print(sci)
print(soc)
