print('\t'"12th Score Details")
tam=int(input("Enter Tamil Mark"'\t'))
eng=int(input("Enter English Mark"'\t'))
mat=int(input("Enter Maths Mark"'\t'))
phy=int(input("Enter Physics Mark"'\t'))
che=int(input("Enter Chemistry Mark"'\t'))
cs=int(input("Enter Computer Mark"'\t'))
print(tam)
print(eng)
print(mat)
print(phy)
print(che)
print(cs)
